# JPA specific configs
spring:
  application:
    name: java-preparation-dev
  profiles:
    active: dev
  h2:
    console:
      enabled: false
      path: /h2-console

java-samples:
  db:
    url: jdbc:postgresql://localhost:3432/test_db
    username: postgres
    password: AppUserPassword123!
    dialect: org.hibernate.dialect.PostgreSQLDialect
    driverClassName: org.postgresql.Driver
    show-sql: true
    dbSchema: public
    dd-auto: update

# Kafka properties
kafka:
  bootstrapServers: localhost:9092
  schemaRegistryUrl: http://localhost:18081
  consumerGroupId: consumer-g1