# JPA specific configs
spring:
  application:
    name: java-preparation-dev
  h2:
    console:
      enabled: false

java-samples:
  db:
    url: ${JDBC_URL}
    username: postgres
    password: Password123!
    dialect: org.hibernate.dialect.PostgreSQLDialect
    driverClassName: org.postgresql.Driver
    show-sql: true
    dbSchema: public
    dd-auto: update

# Kafka properties
kafka:
  bootstrapServers: kafka:9092
  schemaRegistryUrl: http://kafka:18081
  consumerGroupId: consumer-g1