# JPA specific configs
spring:
  application:
    name: java-samples-local
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 1007

java-samples:
  db:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    dialect: org.hibernate.dialect.H2Dialect
    driverClassName: org.h2.Driver
    ddl-auto: update
    show-sql: true
    dbSchema: public
    dd-auto: update