# JPA specific configs
spring:
  application:
    name: java-preparation-local
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 1007

java-samples:
  db:
    show-sql: true
    dbSchema: public
    dd-auto: update

# Kafka properties
kafka:
  bootstrapServers: localhost:9092
  schemaRegistryUrl: http://localhost:18081
  consumerGroupId: consumer-g1