apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka-config
data:
  ZOOKEEPER_CLIENT_PORT: 2181
  ZOOKEEPER_TICK_TIME: 2000
  KAFKA_BROKER_ID: 1
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
  CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
  CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:18081
  CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
  CONFLUENT_METRICS_ENABLE: "true"
  CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
  SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
  SCHEMA_REGISTRY_HOST_NAME: schema-registry
  SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:18081
  CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
  CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:18081"
  CONTROL_CENTER_REPLICATION_FACTOR: 1
  CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
  CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
  CONFLUENT_METRICS_TOPIC_REPLICATION: 1